// Product & site data for Cotton Connection

export const products = [
  {
    id: 1,
    name: 'Egyptian Cotton Bath Towel Set',
    category: 'Towels',
    price: 49.99,
    originalPrice: 64.99,
    rating: 4.9,
    reviews: 124,
    image: '/images/product-towels.png',
    badge: 'Best Seller',
    description: 'Indulge in the ultimate bathing experience with our premium Egyptian cotton towel set. Featuring a luxuriously soft 700 GSM weave, these towels offer exceptional absorbency while remaining incredibly gentle on your skin. Each set includes 2 bath towels, 2 hand towels, and 2 face towels in coordinating colors.',
    details: [
      '100% Egyptian Cotton, 700 GSM',
      'Set of 6 (2 bath, 2 hand, 2 face)',
      'Oeko-Tex certified, safe for sensitive skin',
      'Machine washable, gets softer with each wash',
      'Available in 8 colors'
    ],
    colors: ['White', 'Ivory', 'Sage', 'Grey'],
  },
  {
    id: 2,
    name: 'Luxury Waffle Weave Bathrobe',
    category: 'Bathrobes',
    price: 89.99,
    originalPrice: null,
    rating: 4.8,
    reviews: 86,
    image: '/images/product-bathrobe.png',
    badge: 'New',
    description: 'Wrap yourself in cloud-like comfort with our signature waffle weave bathrobe. Crafted from premium long-staple cotton, this robe features an elegant shawl collar, deep pockets, and a matching self-tie belt. Lightweight yet warm, perfect for year-round wear.',
    details: [
      '100% Long-Staple Cotton',
      'Waffle weave for breathability',
      'Shawl collar with deep pockets',
      'Unisex design, sizes S-XXL',
      'Matching slippers available'
    ],
    colors: ['Cream', 'White', 'Charcoal'],
  },
  {
    id: 3,
    name: 'Sateen Bed Sheet Set — 400 TC',
    category: 'Bed Sheets',
    price: 119.99,
    originalPrice: 149.99,
    rating: 4.9,
    reviews: 203,
    image: '/images/product-bedsheets.png',
    badge: 'Sale',
    description: 'Transform your bedroom into a luxury retreat with our 400 thread count sateen bed sheet set. The silky-smooth finish glides against your skin while the breathable cotton keeps you comfortable all night. Includes a fitted sheet with deep pockets, a flat sheet, and two pillowcases.',
    details: [
      '400 Thread Count Sateen Weave',
      'Includes fitted, flat sheet & 2 pillowcases',
      'Deep pocket fitted sheet (up to 16")',
      'GOTS Organic Cotton certified',
      'Wrinkle-resistant finish'
    ],
    colors: ['Ivory', 'Sage Green', 'Dusty Blue', 'White'],
  },
  {
    id: 4,
    name: 'Decorative Cotton Pillow Covers',
    category: 'Pillow Covers',
    price: 34.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 67,
    image: '/images/product-pillowcovers.png',
    badge: null,
    description: 'Elevate your living space with our artisan-designed decorative pillow covers. Each cover features a unique subtle pattern woven into premium cotton, adding texture and warmth to any sofa, bed, or reading nook. Hidden zipper closure for a clean, polished look.',
    details: [
      '100% Premium Cotton',
      'Set of 2 coordinating designs',
      'Hidden zipper closure',
      '18" x 18" (standard) and 20" x 20" (large)',
      'Insert not included'
    ],
    colors: ['Blush & Gold', 'Sage & Cream', 'Grey & White'],
  },
];

export const collections = [
  {
    id: 'towels',
    name: 'Towels',
    category: 'Towels',
    count: 12,
    image: '/images/product-towels.png',
    heroImage: '/images/product-towels.png',
    description: 'Face, hand & bath towels in premium cotton',
    longDescription: 'Discover our complete range of premium Egyptian cotton towels. From plush bath towels to gentle face towels, each piece is crafted with 700 GSM weave for exceptional softness and absorbency. Available in a curated palette of natural colors.',
    subcategories: ['Face Towels', 'Hand Towels', 'Bath Towels', 'Towel Sets'],
  },
  {
    id: 'bathrobes',
    name: 'Bathrobes',
    category: 'Bathrobes',
    count: 8,
    image: '/images/product-bathrobe.png',
    heroImage: '/images/product-bathrobe.png',
    description: 'Waffle weave, terry cloth & hooded robes',
    longDescription: 'Wrap yourself in our collection of premium bathrobes. From lightweight waffle weave for year-round comfort to plush terry cloth for those cold mornings, each robe features thoughtful details like deep pockets, matching belts, and elegant collars.',
    subcategories: ['Waffle Weave', 'Terry Cloth', 'Hooded Robes', 'Lightweight'],
  },
  {
    id: 'bedsheets',
    name: 'Bed Sheets',
    category: 'Bed Sheets',
    count: 15,
    image: '/images/product-bedsheets.png',
    heroImage: '/images/product-bedsheets.png',
    description: 'Fitted, flat sheets & complete sets',
    longDescription: 'Transform your bedroom into a luxury retreat with our premium bed sheet collection. Available in sateen and percale weaves from 300 to 600 thread count, our sheets offer the perfect balance of silky smoothness and breathable comfort.',
    subcategories: ['Fitted Sheets', 'Flat Sheets', 'Sheet Sets', 'Duvet Covers'],
  },
  {
    id: 'pillowcovers',
    name: 'Pillow Covers',
    category: 'Pillow Covers',
    count: 10,
    image: '/images/product-pillowcovers.png',
    heroImage: '/images/product-pillowcovers.png',
    description: 'Standard, decorative & euro shams',
    longDescription: 'Elevate any room with our artisan-designed pillow covers. From classic solid tones to elegant geometric patterns, each cover is made from premium cotton with hidden zipper closures for a polished, clean look.',
    subcategories: ['Standard Covers', 'Decorative Covers', 'Euro Shams', 'Bolster Covers'],
  },
  {
    id: 'giftsets',
    name: 'Gift Sets',
    category: 'Gift Sets',
    count: 6,
    image: '/images/product-towels.png',
    heroImage: '/images/product-towels.png',
    description: 'Curated bundles for every occasion',
    longDescription: 'The perfect gift for any occasion. Our thoughtfully curated bundles pair our most loved products in beautiful packaging. From spa-day essentials to complete bedroom makeovers, each set is designed to delight.',
    subcategories: ['Bath Bundles', 'Bedroom Bundles', 'Luxury Gift Boxes', 'Wedding Sets'],
  },
];

export const testimonials = [
  {
    id: 1,
    quote: "The softest towels I've ever owned. My bathroom feels like a five-star spa now. I've already ordered two more sets!",
    name: 'Sarah Mitchell',
    role: 'Verified Buyer',
    rating: 5,
    avatar: 'SM',
  },
  {
    id: 2,
    quote: "These bed sheets changed my sleep. So smooth and breathable — I literally never want to get out of bed in the morning.",
    name: 'James Kim',
    role: 'Verified Buyer',
    rating: 5,
    avatar: 'JK',
  },
  {
    id: 3,
    quote: "The bathrobe is absolutely divine. It's like wrapping yourself in a cloud every morning. Worth every penny.",
    name: 'Priya Sharma',
    role: 'Verified Buyer',
    rating: 5,
    avatar: 'PS',
  },
  {
    id: 4,
    quote: "I bought pillow covers as a housewarming gift, and they loved them! Beautiful quality and the packaging was so elegant.",
    name: 'Emma Lewis',
    role: 'Verified Buyer',
    rating: 5,
    avatar: 'EL',
  },
  {
    id: 5,
    quote: "Finally found bed sheets that stay cool in summer and cozy in winter. The sateen finish is gorgeous. Will be buying more!",
    name: 'David Torres',
    role: 'Verified Buyer',
    rating: 5,
    avatar: 'DT',
  },
];

export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'Shop', href: '/shop' },
  { label: 'Collections', href: '/#collections' },
  { label: 'About', href: '/#about' },
  { label: 'Contact', href: '/contact' },
  { label: 'Wishlist', href: '/wishlist' },
];
